### [De&C] Tugas 1
Sebuah lift memiliki daya tampung maksimum sebesar $C$ kg. $N$ orang mahasiswa saat ini berada di lantai 16. Masing-masing berat badan mahasiswa tersebut adalah $b_0, b_1, \dots b_{N-1}$. Karena terdapat agenda mendadak, manajemen gedung meminta perwakilan mahasiswa untuk dapat hadir di ruang rapat di lantai 1. Dengan batasan kapasitas lift, berapa jumlah mahasiswa terbanyak (dan siapa sajakah yang akan ditunjuk) yang sebaiknya diutus untuk mengikuti pertemuan tersebut dengan mobilisasi menggunakan lift?

Selesaikan masalah di atas dengan algoritma berkompleksitas waktu $\mathcal{O}(2^{N})$ dan kompleksitas ruang $\mathcal{O}(N)$. Rancanglah algoritma yang seefisien mungkin untuk kemungkinan *best case* yang mungkin terjadi.

In [17]:
# def bfs(current_position, berat, c, solutions, path_explored, value):
#     queue = []
#     queue.append([current_position, berat, c, path_explored, value])
#     while(len(queue) != 0):
#         current_position, berat, c, path_explored, value = queue[0]
#         queue.pop(0)
#         current_value = value
#         current_value += berat[current_position, kontol]
#         if current_value > c:
#             solutions.append([])
#         else:
#             value += berat[current_position]
#             next_path_explored = path_explored + [berat[current_position]]
#             current_position += 1
#             queue.append(current_position, berat, c, path_explored, value, kontol)
     
# c = int(input("Daya tampung maksimum lift : "))
# berat = int(input("Berat-berat badan mahasiswa : ")).split(" ")
# solutions = []
# bfs(0, berat, c, solutions, [], 0)
def subsets(array):
    result = [[]]
    for element in array:
        result += [j + [element] for j in result]
    return result
def solution(s, c):
    max = []
    if sum(s) <= c:
        return s
    else:
        result = subsets(s)
    for i in result:
        if len(i) > len(max) and sum(i) <= c:
            max = i
    for i in range (len(result)-1,0,-1):
        if len(result[i]) == len(max) and sum(result[i]) <= c:
            return result[i]
    return max

if __name__ == '__main__':
    A = [80, 60, 75, 65, 75, 80, 82, 59, 45, 67]
    c = 500
    result = solution(A, c)
    print(f"Paling banyak terdapat {len(result)} orang yang dapat di tampung oleh lift dengan berat ", end="")
    for i in range(len(result)):
        print(result[i], end=", ")
    print(f"Total berat orang dalam lift = {sum(result)} Kg")

Paling banyak terdapat 7 orang yang dapat di tampung oleh lift dengan berat 65, 75, 80, 82, 59, 45, 67, Total berat orang dalam lift = 473 Kg


### [De&C] Tugas 2

Rancanglah algoritma untuk penyelesaian Masalah Koin Palsu dengan setiap iterasinya membagi total koin ke dalam 3 bagian, sedemikian sehingga efisiensi waktunya $\mathcal{O}(\log_3 N)$ dan efisiensi ruangnya $\mathcal{O}(1)$.

In [ ]:
def balance(leftst, leftfin, rightst, rightfin, fake):
    if leftst <= fake and fake < leftfin:
        return "left"
    if rightst <= fake and fake < rightfin:
        return "right"
    return "same weight"

def findfake(left, right, balancing, fake):
    coins = right - left
    if coins == 1:
        print("Koin palsu adalah koin ", left)
        print("Total penimbangan ", balancing)
        return
    if coins == 2:
        balancing += 1
        print("sisi kiri ", left)
        print("sisi kanan ", right-1)
        result = balance(left, left+1, left+1, right, fake)
        if result == "left":
            print("Pada penimbangan ke-",balancing,", bagian kiri lebih ringan")
            print("Maka koin yang palsu adalah", left)
            print("Total penimbangan ", balancing)
        if result == "right":
            print("Pada penimbangan ke-",balancing,", bagian kanan lebih ringan")
            print("Maka koin yang palsu adalah", right-1)
            print("Total penimbangan ", balancing)
        return        
    print("sisi kiri", left,"sampai", left + coins//3-1)
    print("sisi tengah", left + coins//3,"sampai", left + (coins//3)+(coins//3)-1)
    print("sisi kanan", left + (coins//3)+(coins//3),"sampai", right-1)
    result = balance(left, left + coins//3, left + coins//3, left + (coins//3)+(coins//3), fake)
    balancing += 1
    if result == "left":
        print("Pada penimbangan ke-",balancing,", bagian kiri lebih ringan")
        print("")
        findfake(left, left + coins//3, balancing, fake)
    elif result == "right":
        print("Pada penimbangan ke-",balancing,", bagian tengah lebih ringan")
        print("")
        findfake(left + coins//3, left + (coins//3)+(coins//3), balancing, fake)
    else:
        print("Pada penimbangan ke-",balancing,", bagian kanan lebih ringan")
        print("")
        findfake(left + (coins//3)+(coins//3), right, balancing, fake)

n = int(input("Jumlah koin : "))
fake = int(input("Koin yang palsu (0 s/d (Jumlah koin)-1): "))

findfake(0, n, 0, fake)

Jumlah koin : 1000
Koin yang palsu (0 s/d (Jumlah koin)-1): 9
sisi kiri 0 sampai 332
sisi tengah 333 sampai 665
sisi kanan 666 sampai 999
Pada penimbangan ke- 1 , bagian kiri lebih ringan

sisi kiri 0 sampai 110
sisi tengah 111 sampai 221
sisi kanan 222 sampai 332
Pada penimbangan ke- 2 , bagian kiri lebih ringan

sisi kiri 0 sampai 36
sisi tengah 37 sampai 73
sisi kanan 74 sampai 110
Pada penimbangan ke- 3 , bagian kiri lebih ringan

sisi kiri 0 sampai 11
sisi tengah 12 sampai 23
sisi kanan 24 sampai 36
Pada penimbangan ke- 4 , bagian kiri lebih ringan

sisi kiri 0 sampai 3
sisi tengah 4 sampai 7
sisi kanan 8 sampai 11
Pada penimbangan ke- 5 , bagian kanan lebih ringan

sisi kiri 8 sampai 8
sisi tengah 9 sampai 9
sisi kanan 10 sampai 11
Pada penimbangan ke- 6 , bagian tengah lebih ringan

Koin palsu adalah koin  9
Total penimbangan  6


### [Di&C] Tugas 3

Implementasikan Algoritma Quick Sort dengan efisiensi waktu rata-rata $\mathcal{O}(n \log n)$ dan efisiensi ruang $\mathcal{O}(n \log n)$.

In [ ]:
def quicksort(st, fin, L):
    if st >= fin:
        return
    p = L[st]
    i = st + 1
    j = fin - 1
    if i != j:
        while(i < j):
            while(L[i] <= p):
                i += 1
            while(L[j] > p):
                j -= 1
            if i < j:
                L[i], L[j] = L[j], L[i]
        L[st], L[j] = L[j], L[st]
    quicksort(st, j, L)
    quicksort(j+1, fin, L)

L = [5, 3, 1, 9, 8, 2, 4, 7]
quicksort(0, len(L), L)
print(L)

[1, 2, 3, 4, 5, 7, 8, 9]


### [Di&C] Tugas 4

Implementasikan Algoritma Strassen Matrix Multiplication dengan efisiensi waktu $\mathcal{O}(n^{\log_2 7})$ dan efisiensi ruang $\mathcal{O}(n^2 \log n)$

In [15]:
import numpy as np
import math


def split(matrix, n):
    return matrix[:n, :n], matrix[:n, n:], matrix[n:, :n], matrix[n:, n:]

def matrix_dim(matrix):
    while math.log(len(matrix), 2) < math.ceil(math.log(len(matrix), 2)):
        matrix = np.pad(matrix, (0, 1), mode='constant')
    return matrix

def strassen(a, b):
    n = len(a)
    if n == 1:
        return a * b

    a00, a01, a10, a11 = split(a, n // 2)
    b00, b01, b10, b11 = split(b, n // 2)

    m1 = strassen(a00 + a11, b00 + b11)
    m2 = strassen(a10 + a11, b00)
    m3 = strassen(a00, b01 - b11)
    m4 = strassen(a11, b10 - b00)
    m5 = strassen(a00 + a01, b11)
    m6 = strassen(a10 - a00, b00 + b01)
    m7 = strassen(a01 - a11, b10 + b11)

    C00 = m1 + m4 - m5 + m7
    C01 = m3 + m5
    C10 = m2 + m4
    C11 = m1 + m3 - m2 + m6

    result = np.vstack((np.hstack((C00, C01)), np.hstack((C10, C11))))
    return result

A = np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 6], [9, 10, 11, 12, 13], [13, 14, 15, 16, 17], [2, 2, 2, 2, 2]])
B = np.array([[4, 4, 4, 4, 1], [5, 5, 5, 5, 2], [6, 6, 6, 6, 6], [7, 7, 7, 7, 7], [1, 1, 1, 1, 1]])

print(f"Matrix A: \n{A}")
print(f"Matrix B: \n{B}")
A = matrix_dim(A)
B = matrix_dim(B)

print("\nMatrix multiplication result: \n")

result_matrix = strassen(A, B)
print(result_matrix[:len(A), :len(A)])

Matrix A: 
[[ 1  2  3  4  5]
 [ 5  6  7  8  6]
 [ 9 10 11 12 13]
 [13 14 15 16 17]
 [ 2  2  2  2  2]]
Matrix B: 
[[4 4 4 4 1]
 [5 5 5 5 2]
 [6 6 6 6 6]
 [7 7 7 7 7]
 [1 1 1 1 1]]

Matrix multiplication result: 

[[ 65  65  65  65  56]
 [154 154 154 154 121]
 [249 249 249 249 192]
 [341 341 341 341 260]
 [ 46  46  46  46  34]]


### Tugas Tantangan

Implementasikan Algoritma Closest Pair dengan efisiensi waktu $\mathcal{O}(n\log^2 n)$ dan efisiensi ruang $\mathcal{O}(n\log n)$